config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :groups, only: [:create]
  resources :activities, only: [:index, :show, :new, :create, :update, :edit, :delete]

  # For Login and Signup Modal
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',

    # For facebook authentication
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get '/privacy', to: 'pages#privacy', as: :privacy
  get '/privacy/facebook', to: 'pages#facebook_privacy', as: :facebook_privacy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_activity_card.html.erb
<div class="activity-wrapper">
  <div class="inner-activity boxed">
    <div class="date-info-wrapper">
      <div class="date-info">
        <%= activity.start_time.strftime('%b, %d') %>
      </div>
      <div class="time-info">
        <%= activity.start_time.strftime('%H:%M') %> - <%= activity.end_time.strftime('%H:%M') %>
      </div>
    </div>
    <div class="user-wrapper">
      <div class="photo-wrapper">
        <% id = activity.group.id %>
        <% user_group = UserGroup.find_by(group_id: id) %>
        <% owner = user_group.user %>
        <% first_inital = owner.email[0] %>
        <% second_inital = owner.email.partition('.').last[0] %>
        <% avatar_url = owner.facebook_picture_url || "https://eu.ui-avatars.com/api/?name=#{first_inital}+#{second_inital}" %>
        <%= image_tag avatar_url, class: "avatar-large", alt: "avatar-large" %>
      </div>
    </div>
    <div class="description-wrapper">
      <div class="category">
        <i class="fas fa-book"></i> <%= activity.name %>
      </div>
      <div class="link">
        <i class="fas fa-external-link-alt"></i> <%= link_to activity.link.truncate(45),activity.link %>
      </div>
    </div>
    <div class="actions-wrapper">
      <div class="button-black-inverse"> Join Challenge</div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_login_form.html.erb
<div class="modal fade bd-example-modal-lg"tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div class="omniauth-button">
          <%- if devise_mapping.omniauthable? %>
            <%- resource_class.omniauth_providers.each do |provider| %>
              <%= link_to " Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "#{provider}-signup" %>
            <% end %>
          <% end %>
        </div>
        <p class="form-divider">or</p>
        <div class="errors"></div>
        <%= minimal_form_for(resource_name, :url => session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
            <%= f.input :password,
                required: true,
                input_html: { autocomplete: "current-password" } %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="modal-signup-button">
            <%= f.button :submit, "Log in", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% unless user_signed_in?  %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
      <% end %>
  <% else %>
    <%= link_to activities_path, class: "navbar-brand" do %>
      <%= image_tag "logo-neg.png" %>
      <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to "Add Challenge", new_activity_path, class: "button-black" %>
        <li class="nav-item active">
          <%= link_to "Home", activities_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% first_inital = current_user.email[0] %>
          <% second_inital = current_user.email.partition('.').last[0] %>
          <% avatar_url = current_user.facebook_picture_url || "https://eu.ui-avatars.com/api/?name=#{first_inital}+#{second_inital}" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add Challenge", "activities/new", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", "", data: {toggle: "modal", target: ".bd-example-modal-lg"}, class: "button-black" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%= render 'shared/login_form' %>

app/views/shared/_signup_form.html.erb
<div class="modal fade bd-example-modal-lg modal-signup"tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div class="omniauth-button">
          <%- if devise_mapping.omniauthable? %>
            <%- resource_class.omniauth_providers.each do |provider| %>
              <%= link_to " Sign up with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "#{provider}-signup" %>
            <% end %>
          <% end %>
        </div>
        <p class="form-divider">or</p>
        <div class="errors"></div>
        <%= minimal_form_for(resource_name, :url => registration_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <div class="form-row">
              <div class="form-group col-md-6">
                <%= f.input :first_name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
              </div>
              <div class="form-group col-md-6">
                <%= f.input :last_name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
              </div>
            </div>
            <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
            <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
            <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="modal-signup-button">
            <%= f.button :submit, "Sign Up", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>